image: python:3.11

stages:
  - test

pytest:
  stage: test
  script:
    - python -m pip install --upgrade pip
    - pip install -e ".[dev]"
    - pytest --cov=atomvoxelizer --cov-report=term-missing --cov-report=xml:coverage.xml tests/
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
